### ISSUE TITLE
Error when initializing wallet

### ISSUE THREAD

**Issue by hvuhsg** [tonfactory/tonsdk#21]
Hi I am getting this error when trying to send init external message for new wallet:
"error": "LITE_SERVER_UNKNOWN: cannot apply external message to current state : Failed to unpack account state",

```python   
async def initialize(self):
        result = self.wallet.create_init_external_message()
        boc = result["message"].to_boc(False)
        return await self.client.send_boc(boc)
```

using toncenter api

**Comment by yungwine** [comment]
> Hi I am getting this error when trying to send init external message for new wallet:
> 
> "error": "LITE_SERVER_UNKNOWN: cannot apply external message to current state : Failed to unpack account state",
> 
> 
> 
> ```python   
> 
> async def initialize(self):
> 
>         result = self.wallet.create_init_external_message()
> 
>         boc = result["message"].to_boc(False)
> 
>         return await self.client.send_boc(boc)
> 
> ```
> 
> 
> 
> using toncenter api

you should first top up the wallet you want to deploy.
